template = "https://github.com/giellalt/template-lang-und"
rev_id = 25
template_sha = "4f72fd073f23ca8376894285367582769d9ff2f2"

[replacements]
__UND2C__ = "rmu"
__UNDEFINED__ = "Tavringer Romani"
__UND__ = "rmu"
