template = "https://github.com/giellalt/template-lang-und"
rev_id = 9
template_sha = "dff17bdd04bb3bb235ba071f584311e8fd41bc02"

[replacements]
__UND2C__ = "rmu"
__UNDEFINED__ = "Tavringer Romani"
__UND__ = "rmu"
