template = "https://github.com/giellalt/template-lang-und"
rev_id = 23
template_sha = "b28e5ae28e301b62a0b6bf73b7b113ac4199ad54"

[replacements]
__UND2C__ = "rmu"
__UNDEFINED__ = "Tavringer Romani"
__UND__ = "rmu"
