[package]
name = "rmu"
human_name = "Tavringer Romani"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.rmu]
filename = "rmu-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-rmu"
platform = "windows"
uuid = "8B865450-2219-4083-BA0A-2DE1C47A966D"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.rmu"
package = "speller-rmu"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-rmu-mso"
platform = "windows"
uuid = "1CE95BC5-DCFC-4649-803E-C67AD4121937"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-rmu"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
